use_frameworks!

platform :ios, '10.0'

target 'VisualSwiftPod1_Example' do
  pod 'VisualSwiftPod1', :path => '../'

  target 'VisualSwiftPod1_Tests' do
    inherit! :search_paths

    pod 'VisualOCPod1', :git => 'https://@github.com/cx-z/VisualOCPod1.git', :tag => '0.1.1'
  end
end
